name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: rfid_bridge
            asset_name: rfid_bridge-linux-x86_64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: rfid_bridge.exe
            asset_name: rfid_bridge-windows-x86_64.exe

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxdo-dev pkg-config libudev-dev

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary (Linux)
        if: matrix.os != 'windows-latest'
        run: cp target/${{ matrix.target }}/release/${{ matrix.artifact }} ${{ matrix.asset_name }}

      - name: Rename binary (Windows)
        if: matrix.os == 'windows-latest'
        run: copy target\${{ matrix.target }}\release\${{ matrix.artifact }} ${{ matrix.asset_name }}

      # Ganti upload release -> upload artifact biasa
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
